package sk000801.SQL;

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID


-- DATE_FORMAT 에서 %Y를 해야 4자리 연도를 모두 출력할 수 있듬!
-- %y는 2자리 연도
-- MONTH()만 해주면 원하는 달을 출력해줄 수 있나봄!