SELECT A.PRODUCT_ID, A.PRODUCT_NAME, A.PRICE*SUM(B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE CONCAT('2022-05', '%')
GROUP BY A.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC

--GROUP BY 언제 쓰이는지 제대로 알아보기!