SELECT YEAR(b.SALES_DATE) AS YEAR, MONTH(b.SALES_DATE) AS MONTH, a.GENDER, COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a JOIN ONLINE_SALE b ON a.USER_ID = b.USER_ID
WHERE a.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC