SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE, 
if(TIMESTAMPDIFF(DAY, START_DATE, END_DATE)+1 >= 30, '장기 대여', '단기 대여') RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09-%'
ORDER BY HISTORY_ID DESC

--날짜 차이는 +1을 해줘야됨
--그냥 DATEDIFF는 인자 2개 (큰, 작)
--TIMESTAMPDIFF(단위,작,큰)