SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a JOIN ANIMAL_OUTS b
ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE LIKE CONCAT('Intact','%') 
AND (b.SEX_UPON_OUTCOME = 'Spayed Female' 
OR b.SEX_UPON_OUTCOME = 'Neutered Male')