SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT a.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT a.USER_ID)/COUNT,1) AS PURCHASER_RATIO
FROM ONLINE_SALE a
INNER JOIN 
    (SELECT USER_ID, COUNT(*) OVER() AS COUNT 
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
    ) b on b.USER_ID = a.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC

--INNER JOIN에 대해 정리해볼것..