SELECT CAR_ID, if(MAX(END_DATE) >= '2022-10-16', '대여중', '대여 가능') AVAILABILITY    
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16'
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

--if문을 통해 새로운 열을 하나 생성할 수 있다는 거 !!!