SELECT A.HISTORY_ID, ROUND((A.DAILY_FEE * (1.0-IFNULL(C.DISCOUNT_RATE*0.01,0)))*A.DAYS, 0) FEE
FROM (
    SELECT CRCR.HISTORY_ID, CRCC.DAILY_FEE, (DATEDIFF(END_DATE, START_DATE)+1) DAYS,
    CASE WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 90 THEN '90일 이상'
    WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 30 THEN '30일 이상'
    WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 7 THEN '7일 이상' END DIFF
    FROM CAR_RENTAL_COMPANY_CAR CRCC
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCR
    ON CRCC.CAR_ID = CRCR.CAR_ID WHERE CRCC.CAR_TYPE = '트럭'
) A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.DIFF = C.DURATION_TYPE
AND C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC