SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(1-B.DISCOUNT_RATE/100)) FEE
FROM CAR_RENTAL_COMPANY_CAR A JOIN (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-00'
    AND START_DATE < '2022-12-00'
)
AND A.CAR_TYPE IN ('세단', 'SUV')
HAVING FEE >= 500000 AND FEE <= 2000000
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC